---
engine:
  name: podman

containers:
  - name: ubuntu-22.04
    image: ubuntu-systemd:22.04
  - name: rockylinux-9.1
    image: rockylinux-systemd:9.1

provisioner:
  name: ansible
  extra_args:
    - --diff
  env:
    ANSIBLE_NOCOLOR: False

verifier:
  name: goss
